# Generated by Django 3.0.4 on 2020-09-28 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='responded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
    ]
