# Generated by Django 3.1.4 on 2020-12-28 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cruise', '0004_auto_20201227_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=40, null=True)),
                ('lastName', models.CharField(max_length=40, null=True)),
                ('emailAddress', models.EmailField(max_length=250, null=True)),
                ('phoneNumber', models.CharField(max_length=15, null=True)),
                ('message', models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
