# Generated by Django 3.1.4 on 2020-12-28 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruise', '0007_auto_20201228_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='emailAddress',
            field=models.EmailField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='firstName',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='lastName',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='message',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='phoneNumber',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='seen',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
