# Generated by Django 3.1.4 on 2020-12-29 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cruise', '0009_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='firstName',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='message',
            name='lastName',
        ),
    ]
