# Generated by Django 3.1.4 on 2020-12-29 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruise', '0010_auto_20201229_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='cost',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
