# Generated by Django 3.1.4 on 2020-12-30 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cruise', '0011_auto_20201229_1319'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service',
            new_name='Business',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='service',
            new_name='product',
        ),
    ]
